/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;
import juegoahorcado.Partida;

/**
 *
 * @author juank
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private Partida nuevaPartida;
    private ArrayList<JTextField> letras;
    private ArrayList<JLabel> guiones;
    private int turno, ultimoAdivinador, puntosJugador1, puntosJugador2, contadorPartidas;
    private String palabraAdivinada;

    public VentanaPrincipal() {
        initComponents();
        letras = new ArrayList();
        guiones = new ArrayList();

        letras.add(letra1);
        letras.add(letra2);
        letras.add(letra3);
        letras.add(letra4);
        letras.add(letra5);
        letras.add(letra6);
        letras.add(letra7);
        letras.add(letra8);
        letras.add(letra9);
        letras.add(letra10);

        guiones.add(guion1);
        guiones.add(guion2);
        guiones.add(guion3);
        guiones.add(guion4);
        guiones.add(guion5);
        guiones.add(guion6);
        guiones.add(guion7);
        guiones.add(guion8);
        guiones.add(guion9);
        guiones.add(guion10);

        puntosJugador1 = 0;
        puntosJugador2 = 0;
        palabraAdivinada = "";
        ultimoAdivinador = 1;
        turno = 1;
        reiniciarPartida();
    }

    public void reiniciarPartida() {
        nuevaPartida = new Partida();
        botonReiniciarJuego.setEnabled(false);
        botonAceptarLetra.setEnabled(false);
        botonAceptarLetraAdivinada.setEnabled(false);
        botonAceptarPalabraOculta.setEnabled(true);
        botonSiguientePartida.setEnabled(false);
        botonAñadirFallo.setEnabled(false);
        for (int i = 0; i < 10; i++) {
            letras.get(i).setText("");
            letras.get(i).setVisible(false);
            guiones.get(i).setVisible(false);
        }

        if (ultimoAdivinador == 1) {
            ultimoAdivinador = 2;
            turno = 1;
            txtAdivinador.setText("ADIVINADOR: JUGADOR 2");
        } else {
            ultimoAdivinador = 1;
            turno = 2;
            txtAdivinador.setText("ADIVINADOR: JUGADOR 1");
        }

        if (turno == 1) {
            txtTurnoJugadorX.setText("TURNO: JUGADOR 1");

        } else {
            txtTurnoJugadorX.setText("TURNO: JUGADOR 2");
        }
        
         
    }

    public void pasaTurno() {

        if (turno == 1) {
            turno = 2;
            txtTurnoJugadorX.setText("TURNO: JUGADOR 2");
            txtTurnoJugadorX.setForeground(Color.red);

        } else {
            turno = 1;
            txtTurnoJugadorX.setForeground(Color.blue);
            txtTurnoJugadorX.setText("TURNO: JUGADOR 1");
        }

    }

    public boolean finJuego() {
        if ((5 - puntosJugador1) == 2 || (5 - puntosJugador2) == 2) {
            if (puntosJugador1 > puntosJugador2) {
               
                txtGanador.setText("GANADOR JUGADOR 1");
                return true;
            } else {
               
                txtGanador.setText("GANADOR JUGADOR 2");
                return true;
            }
        } else {
            return false;
        }

    }

    public void aumentarPuntosJugador(int jugadorID) {
        if (jugadorID == 1) {
            this.puntosJugador1++;
        } else {
            this.puntosJugador2++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new javax.swing.JPanel();
        imagenLabel = new javax.swing.JLabel();
        txtPalabraOculta = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        botonAceptarPalabraOculta = new javax.swing.JButton();
        panelPuntos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPuntosJ1 = new javax.swing.JLabel();
        txtPuntosJ2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonAceptarLetra = new javax.swing.JButton();
        txtTurnoJugadorX = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelPalabra = new javax.swing.JPanel();
        letra1 = new javax.swing.JTextField();
        guion1 = new javax.swing.JLabel();
        letra2 = new javax.swing.JTextField();
        guion2 = new javax.swing.JLabel();
        letra3 = new javax.swing.JTextField();
        guion3 = new javax.swing.JLabel();
        letra4 = new javax.swing.JTextField();
        guion4 = new javax.swing.JLabel();
        letra5 = new javax.swing.JTextField();
        guion5 = new javax.swing.JLabel();
        letra6 = new javax.swing.JTextField();
        guion6 = new javax.swing.JLabel();
        guion7 = new javax.swing.JLabel();
        letra7 = new javax.swing.JTextField();
        guion8 = new javax.swing.JLabel();
        letra8 = new javax.swing.JTextField();
        guion9 = new javax.swing.JLabel();
        letra9 = new javax.swing.JTextField();
        botonAceptarLetraAdivinada = new javax.swing.JButton();
        letra10 = new javax.swing.JTextField();
        guion10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtAdivinador = new javax.swing.JLabel();
        botonSiguientePartida = new javax.swing.JButton();
        botonAñadirFallo = new javax.swing.JButton();
        botonReiniciarJuego = new javax.swing.JButton();
        txtGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen inicial.png"))); // NOI18N

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenLabel)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenLayout.createSequentialGroup()
                .addComponent(imagenLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtPalabraOculta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalabraOcultaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("INTRODUZCA PALABRA (MÁXIMO 10 LETRAS)");

        botonAceptarPalabraOculta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonAceptarPalabraOculta.setText("ACEPTAR");
        botonAceptarPalabraOculta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarPalabraOcultaActionPerformed(evt);
            }
        });

        panelPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("JUGADOR 1");

        jLabel5.setText("JUGADOR 2");

        txtPuntosJ1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPuntosJ1.setText("0");

        txtPuntosJ2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPuntosJ2.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("PUNTOS");

        javax.swing.GroupLayout panelPuntosLayout = new javax.swing.GroupLayout(panelPuntos);
        panelPuntos.setLayout(panelPuntosLayout);
        panelPuntosLayout.setHorizontalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panelPuntosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtPuntosJ1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPuntosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPuntosLayout.createSequentialGroup()
                        .addComponent(txtPuntosJ2)
                        .addGap(56, 56, 56))))
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPuntosLayout.setVerticalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuntosJ1)
                    .addComponent(txtPuntosJ2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        botonAceptarLetra.setText("ACEPTAR");
        botonAceptarLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarLetraActionPerformed(evt);
            }
        });

        txtTurnoJugadorX.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTurnoJugadorX.setForeground(new java.awt.Color(255, 51, 102));
        txtTurnoJugadorX.setText("TURNO: JUGADOR 1");

        jLabel7.setText("INTRODUZCA LETRA:");

        panelPalabra.setBackground(new java.awt.Color(76, 153, 140));
        panelPalabra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPalabra.setForeground(new java.awt.Color(175, 235, 192));

        letra1.setBackground(new java.awt.Color(76, 153, 140));
        letra1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra1.setToolTipText("");
        letra1.setActionCommand("<Not Set>");
        letra1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra1ActionPerformed(evt);
            }
        });

        guion1.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion1.setText("_____________");

        letra2.setBackground(new java.awt.Color(76, 153, 140));
        letra2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra2.setToolTipText("");
        letra2.setActionCommand("<Not Set>");
        letra2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });

        guion2.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion2.setText("_____________");

        letra3.setBackground(new java.awt.Color(76, 153, 140));
        letra3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra3.setToolTipText("");
        letra3.setActionCommand("<Not Set>");
        letra3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra3ActionPerformed(evt);
            }
        });

        guion3.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion3.setText("_____________");

        letra4.setBackground(new java.awt.Color(76, 153, 140));
        letra4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra4.setToolTipText("");
        letra4.setActionCommand("<Not Set>");
        letra4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra4ActionPerformed(evt);
            }
        });

        guion4.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion4.setText("_____________");

        letra5.setBackground(new java.awt.Color(76, 153, 140));
        letra5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra5.setToolTipText("");
        letra5.setActionCommand("<Not Set>");
        letra5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra5ActionPerformed(evt);
            }
        });

        guion5.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion5.setText("_____________");

        letra6.setBackground(new java.awt.Color(76, 153, 140));
        letra6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra6.setToolTipText("");
        letra6.setActionCommand("<Not Set>");
        letra6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra6ActionPerformed(evt);
            }
        });

        guion6.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion6.setText("_____________");

        guion7.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion7.setText("_____________");

        letra7.setBackground(new java.awt.Color(76, 153, 140));
        letra7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra7.setToolTipText("");
        letra7.setActionCommand("<Not Set>");
        letra7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra7ActionPerformed(evt);
            }
        });

        guion8.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion8.setText("_____________");

        letra8.setBackground(new java.awt.Color(76, 153, 140));
        letra8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra8.setToolTipText("");
        letra8.setActionCommand("<Not Set>");
        letra8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra8ActionPerformed(evt);
            }
        });

        guion9.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion9.setText("_____________");

        letra9.setBackground(new java.awt.Color(76, 153, 140));
        letra9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra9.setToolTipText("");
        letra9.setActionCommand("<Not Set>");
        letra9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra9ActionPerformed(evt);
            }
        });

        botonAceptarLetraAdivinada.setText("ACEPTAR");
        botonAceptarLetraAdivinada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarLetraAdivinadaActionPerformed(evt);
            }
        });

        letra10.setBackground(new java.awt.Color(76, 153, 140));
        letra10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letra10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        letra10.setToolTipText("");
        letra10.setActionCommand("<Not Set>");
        letra10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        letra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra10ActionPerformed(evt);
            }
        });

        guion10.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N
        guion10.setText("_____________");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 3)); // NOI18N

        javax.swing.GroupLayout panelPalabraLayout = new javax.swing.GroupLayout(panelPalabra);
        panelPalabra.setLayout(panelPalabraLayout);
        panelPalabraLayout.setHorizontalGroup(
            panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPalabraLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra1)
                    .addComponent(guion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra2)
                    .addComponent(guion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra3)
                    .addComponent(guion3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra4)
                    .addComponent(guion4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra5)
                    .addComponent(guion5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra6)
                    .addComponent(guion6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra7)
                    .addComponent(guion7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra8)
                    .addComponent(guion8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letra9)
                    .addComponent(guion9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPalabraLayout.createSequentialGroup()
                        .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(botonAceptarLetraAdivinada)
                        .addGap(25, 25, 25))
                    .addGroup(panelPalabraLayout.createSequentialGroup()
                        .addComponent(guion10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelPalabraLayout.setVerticalGroup(
            panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPalabraLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPalabraLayout.createSequentialGroup()
                        .addComponent(letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guion8, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guion9, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guion10, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPalabraLayout.createSequentialGroup()
                        .addComponent(letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guion7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelPalabraLayout.createSequentialGroup()
                            .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guion6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPalabraLayout.createSequentialGroup()
                            .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guion5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPalabraLayout.createSequentialGroup()
                                .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guion4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPalabraLayout.createSequentialGroup()
                                .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guion3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPalabraLayout.createSequentialGroup()
                                .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guion2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPalabraLayout.createSequentialGroup()
                                .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guion1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(botonAceptarLetraAdivinada))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        txtAdivinador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAdivinador.setText("ADIVINADOR: JUGADOR 1");

        botonSiguientePartida.setText("SIGUIENTE PARTIDA");
        botonSiguientePartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguientePartidaActionPerformed(evt);
            }
        });

        botonAñadirFallo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonAñadirFallo.setText("AÑADIR ELEMENTO");
        botonAñadirFallo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirFalloActionPerformed(evt);
            }
        });

        botonReiniciarJuego.setText("JUGAR DE NUEVO");
        botonReiniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReiniciarJuegoActionPerformed(evt);
            }
        });

        txtGanador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtPalabraOculta)
                                                .addGap(18, 18, 18)
                                                .addComponent(botonAceptarPalabraOculta)))
                                        .addGap(69, 69, 69)
                                        .addComponent(txtTurnoJugadorX))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(315, 315, 315)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(txtAdivinador))
                                            .addComponent(panelPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAñadirFallo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(botonAceptarLetra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGanador)
                                .addGap(140, 140, 140))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botonSiguientePartida)
                        .addGap(26, 26, 26)
                        .addComponent(botonReiniciarJuego)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTurnoJugadorX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonAceptarPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAdivinador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAceptarLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGanador)
                        .addGap(5, 5, 5)))
                .addComponent(botonAñadirFallo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiguientePartida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPalabraOcultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalabraOcultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalabraOcultaActionPerformed

    private void botonAceptarPalabraOcultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarPalabraOcultaActionPerformed
        // TODO add your handling code here:
        this.nuevaPartida.setPalabraOculta(txtPalabraOculta.getText());
        for (int i = 0; i < txtPalabraOculta.getText().length(); i++) {
            letras.get(i).setVisible(true);
            guiones.get(i).setVisible(true);
        }
        pasaTurno();
        botonAceptarPalabraOculta.setEnabled(false);
        botonAceptarLetra.setEnabled(true);
        


    }//GEN-LAST:event_botonAceptarPalabraOcultaActionPerformed

    private void botonAceptarLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarLetraActionPerformed
        // TODO add your handling code here:

        pasaTurno();
        if (this.nuevaPartida.LetraAdivinada(txtLetra.getText())) {
            botonAceptarLetra.setEnabled(false);
            botonAceptarLetraAdivinada.setEnabled(true);

        } else {
            /*if(ultimoAdivinador ==1){
            
                aumentarPuntosJugador(2);
            
            }else{
                aumentarPuntosJugador(1);
            
            }
             */
            botonAñadirFallo.setEnabled(true);

        }

    }//GEN-LAST:event_botonAceptarLetraActionPerformed

    private void letra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra10ActionPerformed

    private void letra9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra9ActionPerformed

    private void letra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra8ActionPerformed

    private void letra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra7ActionPerformed

    private void letra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra6ActionPerformed

    private void letra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra5ActionPerformed

    private void letra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra4ActionPerformed

    private void letra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra3ActionPerformed

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra2ActionPerformed

    private void letra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra1ActionPerformed

    private void botonAceptarLetraAdivinadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarLetraAdivinadaActionPerformed
        // TODO add your handling code here:

        pasaTurno();

        for (int i = 0; i < nuevaPartida.getPalabraOculta().length(); i++) {
            palabraAdivinada += letras.get(i).getText();
        }

        if (nuevaPartida.finPartida()) {

            botonAceptarPalabraOculta.setEnabled(false);
            botonAceptarLetra.setEnabled(false);
            botonAñadirFallo.setEnabled(false);
            botonAceptarLetraAdivinada.setEnabled(false);

            botonSiguientePartida.setEnabled(true);
            if (ultimoAdivinador == 1) {

                aumentarPuntosJugador(1);

            } else {
                aumentarPuntosJugador(2);

            }

        } else {
            botonAceptarLetra.setEnabled(true);
        }

        txtPuntosJ1.setText(puntosJugador1 + "");
        txtPuntosJ2.setText(puntosJugador2 + "");
        botonAceptarLetraAdivinada.setEnabled(false);

        if (finJuego()) {
            
            
            botonReiniciarJuego.setEnabled(true);
            botonAceptarPalabraOculta.setEnabled(false);
            botonAceptarLetra.setEnabled(false);
            botonAñadirFallo.setEnabled(false);
            botonAceptarLetraAdivinada.setEnabled(false);
            botonSiguientePartida.setEnabled(false);
            

        }


    }//GEN-LAST:event_botonAceptarLetraAdivinadaActionPerformed

    private void botonAñadirFalloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirFalloActionPerformed
        // TODO add your handling code here:
        pasaTurno();
        switch (nuevaPartida.getFallos()) {

            case 1:
                imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen0.png")));
                break;
            case 2:
                imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen1.png")));
                break;
            case 3:
                imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen 2.png")));
                break;
            case 4:
                imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen 3.png")));
                break;
            case 5:
                imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen 4.png")));
                break;
            case 6:
                imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen final.png")));

                if (ultimoAdivinador == 1) {

                    aumentarPuntosJugador(2);

                } else {
                    aumentarPuntosJugador(1);

                }

                txtPuntosJ1.setText(puntosJugador1 + "");
                txtPuntosJ2.setText(puntosJugador2 + "");
                break;

        }

        botonAceptarLetra.setEnabled(true);
        botonAñadirFallo.setEnabled(false);

        if (nuevaPartida.finPartida()) {
            botonAceptarPalabraOculta.setEnabled(false);
            botonAceptarLetra.setEnabled(false);
            botonAñadirFallo.setEnabled(false);
            botonAceptarLetraAdivinada.setEnabled(false);

            botonSiguientePartida.setEnabled(true);

        }

        if (finJuego()) {
            botonReiniciarJuego.setEnabled(true);
            botonAceptarPalabraOculta.setEnabled(false);
            botonAceptarLetra.setEnabled(false);
            botonAñadirFallo.setEnabled(false);
            botonAceptarLetraAdivinada.setEnabled(false);
            botonSiguientePartida.setEnabled(false);

        }
    }//GEN-LAST:event_botonAñadirFalloActionPerformed

    private void botonSiguientePartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguientePartidaActionPerformed
        // TODO add your handling code here:

        reiniciarPartida();
        imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen inicial.png")));
    }//GEN-LAST:event_botonSiguientePartidaActionPerformed

    private void botonReiniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReiniciarJuegoActionPerformed
        // TODO add your handling code here:
        reiniciarPartida();
        imagenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen inicial.png")));
        puntosJugador1 = 0;
        puntosJugador2 = 0;
        palabraAdivinada = "";
        ultimoAdivinador = 1;
        turno = 1;
        txtGanador.setText("");
        
        txtPuntosJ1.setText(puntosJugador1 + "");
        txtPuntosJ2.setText(puntosJugador2 + "");

    }//GEN-LAST:event_botonReiniciarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarLetra;
    private javax.swing.JButton botonAceptarLetraAdivinada;
    private javax.swing.JButton botonAceptarPalabraOculta;
    private javax.swing.JButton botonAñadirFallo;
    private javax.swing.JButton botonReiniciarJuego;
    private javax.swing.JButton botonSiguientePartida;
    private javax.swing.JLabel guion1;
    private javax.swing.JLabel guion10;
    private javax.swing.JLabel guion2;
    private javax.swing.JLabel guion3;
    private javax.swing.JLabel guion4;
    private javax.swing.JLabel guion5;
    private javax.swing.JLabel guion6;
    private javax.swing.JLabel guion7;
    private javax.swing.JLabel guion8;
    private javax.swing.JLabel guion9;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField letra1;
    private javax.swing.JTextField letra10;
    private javax.swing.JTextField letra2;
    private javax.swing.JTextField letra3;
    private javax.swing.JTextField letra4;
    private javax.swing.JTextField letra5;
    private javax.swing.JTextField letra6;
    private javax.swing.JTextField letra7;
    private javax.swing.JTextField letra8;
    private javax.swing.JTextField letra9;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelPalabra;
    private javax.swing.JPanel panelPuntos;
    private javax.swing.JLabel txtAdivinador;
    private javax.swing.JLabel txtGanador;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JPasswordField txtPalabraOculta;
    private javax.swing.JLabel txtPuntosJ1;
    private javax.swing.JLabel txtPuntosJ2;
    private javax.swing.JLabel txtTurnoJugadorX;
    // End of variables declaration//GEN-END:variables
}
